CREATE TABLE IF NOT EXISTS AMINALS(
    NAME VARCHAR(16) PRIMARY KEY,
    AVERAGE_LIFE_SPAN INT,
    NUMBER_LEGS INT,
    HABITAT VARCHAR(10)
);
-- CREATE TABLE TEST(ID INT PRIMARY KEY, NAME VARCHAR(255));